version: "3.4"

services: 
  bootnode:
    container_name: bootnode
    image: hyperledger/besu:latest
    entrypoint:
      - /bin/bash
      - -c
      - |
        /opt/besu/bin/besu --data-path=/opt/besu/data \
        --genesis-file=/opt/besu/genesis.json \
        --rpc-http-enabled --rpc-http-cors-origins="*" \
        --rpc-http-api=ADMIN,ETH,NET,PERM,QBFT --host-allowlist="*";

    volumes:
      - ./genesis.json:/opt/besu/genesis.json
      - ./node/data:/opt/besu/data
    ports:
      - 8545:8545
      - 30303:30303